language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm install -g create-react-app
  - npm test
  - npm run build
  - cd client && npm install --save gh-pages
  - npm install
  - npm run deploy